#!/bin/sh

# Modelled loosely after the volume-helper script provded with sway,
# located at /usr/libexec/sway/volume-helper if installed


SINK="@DEFAULT_SINK@"

function change {
	amixer sset Master $2%$1
	VOLUME=$(pactl get-sink-volume $SINK \
		| sed -e '/.*balance.*/d;s/.* \([[:digit:]]\+\)%.*/\1/')
	notify-send \
		--app-name herbstluft \
		-t 600 \
		-h string:x-canonical-private-synchronous:volume \
		-h "int:value:$VOLUME" \
		-e \
		"Volume: $VOLUME%"
}

function mute {
	amixer sset Master toggle
	MSG="Audio Unmuted!! Play that music, buddy!"
	case $(pactl get-sink-mute "$SINK") in
		*yes)
			MSG="Audio Muted."
			;;
	esac
	notify-send \
		--app-name herbstluft \
		-t 1000 \
		"$MSG"
}

case $1 in
	mute) mute;;
	*) change $@;;
esac
